name: Testing
on: [push]
jobs:
  e2e:
    name: 'Build + E2E tests'
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    env:
      NODE_ENV: test
      NEXTAUTH_SECRET: supersecret
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1

      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install deps (with cache)
        run: pnpm install

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - name: Setup Prisma
        run: pnpm prebuild

      - run: pnpm build
      - run: pnpm test-e2e

      - name: Check types
        run: pnpm tsc

  unit:
    name: 'Unit tests + typecheck'
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    env:
      NODE_ENV: test
      NEXTAUTH_SECRET: supersecret
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1

      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install deps (with cache)
        run: pnpm install

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - name: Setup Prisma
        run: pnpm prebuild

      - run: pnpm test-unit
      - run: pnpm tsc

  lint:
    name: 'Lint and Prettier'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1

      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install deps (with cache)
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

      - name: Run Prettier
        run: pnpm format:check